name: docker-manifest-create-action
description: Create a multi-architecture Docker image in GitHub Actions

inputs:
  tags:
    description: tags of destination images (multi-line string)
    required: true
  digests:
    description: digests of source images (comma separated)
    required: false
  suffixes:
    description: suffixes of source images (multi-line string)
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
